# docker-compose version
version: "3.6"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
    environment:
      NODE_ENV: &global_env development

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    depends_on:
      - server
    ports:
      - 3000:3000
    environment:
      NODE_ENV: *global_env

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - server
      - client
